# docker-compose.yml
version: '3.8'

services:
  rag-api:
    build: .
    image: rag-api:v1
    container_name: rag-assistant
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

# Optional: Add a volume for explicit management
volumes:
  chroma_data:
    driver: local